default_platform(:ios)
platform :ios do
      desc “Install pod dependencies”
      lane :install_pods do
         cocoapods(
             podfile: PODFILE_PATH,
             use_bundle_exec: false)
end
      
      desc "Incrementing Build Number"
      lane :increment_build do
           current_build_number = latest_testflight_build_number(version: "1.0")
           increment_build_number(
           build_number: current_build_number + 1
           )
      end
      desc “Archive and Build IPA”
      lane :build_ipa do
       install_pods
       increment_build
          gym(
             workspace: WORKSPACE_NAME,
             scheme: SCHEME_NAME,
             output_directory: PATH_FOR_IPA,
             output_name: IPA_NAME,
             export_method: “app-store”,
             include_bitcode: false,
             clean: true)
       end
end